# Dockerfile.validation
FROM public.ecr.aws/lambda/python:3.12

# WORKDIR /src

# Install GCC and required build tools
RUN dnf install -y gcc gcc-c++ python3-devel

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy shared modules
COPY config/config.yaml config/config.yaml 
COPY params.yaml params.yaml
COPY schema.yaml schema.yaml
COPY src/__init__.py src/__init__.py
COPY src/config /src/config
COPY src/constants /src/constants
COPY src/utils /src/utils
COPY src/static /src/static
COPY src/entity /src/entity

# Copy pipeline and its required component
COPY src/pipelines/data_validation_pipeline.py /src/pipelines/data_validation_pipeline.py
COPY src/components/data_validation.py /src/components/data_validation.py

# Set the entry point for the pipeline
CMD ["src.pipelines.data_validation_pipeline.lambda_handler"]