artifacts_root: opt/ml/processing/artifacts

data_ingestion:
  root_dir: opt/ml/processing/artifacts/data_ingestion
  video_games_item: opt/ml/processing/artifacts/data_ingestion/meta_Video_Games.jsonl
  video_games_user: opt/ml/processing/artifacts/data_ingestion/Video_Games.jsonl
  user_df_number: 2000
  user_df_output_path: opt/ml/processing/artifacts/data_ingestion/user_df.csv
  item_df_output_path: opt/ml/processing/artifacts/data_ingestion/item_df.csv

data_validation:
  root_dir: opt/ml/processing/artifacts/data_validation
  video_games_item: opt/ml/processing/artifacts/data_validation/validation_meta_Video_Games.jsonl
  video_games_user: opt/ml/processing/artifacts/data_validation/validation_Video_Games.jsonl
  output: opt/ml/processing/artifacts/data_validation/status.json

data_transformation:
  root_dir: opt/ml/processing/artifacts/data_transformation
  video_games_item: opt/ml/processing/artifacts/data_ingestion/item_df.csv
  video_games_user: opt/ml/processing/artifacts/data_ingestion/user_df.csv
  data_validation_status: opt/ml/processing/artifacts/data_validation/status.json
  output_path_df: opt/ml/processing/artifacts/data_transformation/merged_data_weight.csv

model_trainer:
  root_dir: opt/ml/processing/artifacts/model_trainer
  input_data: opt/ml/processing/artifacts/data_transformation/merged_data_weight.csv
  model_path: opt/ml/processing/artifacts/model_trainer/colab_filter_model.pkl
  cosine_sim: cosine_scores.npy
  indices_name: indices.pkl
  content_df_path: opt/ml/processing/artifacts/model_trainer/content_df.csv

prediction:
  colab_model_path: opt/ml/processing/artifacts/model_trainer/colab_filter_model.pkl
  cosine_sim_path: opt/ml/processing/artifacts/model_trainer/cosine_scores.npy
  indices_path: opt/ml/processing/artifacts/model_trainer/indices.pkl
  content_df_path: opt/ml/processing/artifacts/model_trainer/content_df.csv